package it.drwolf.slot.prefs;

public enum PreferenceKey {

	ALFRESCO_LOCATION, ALFRESCO_ADMIN_USER, ALFRESCO_ADMIN_PWD, ALFRESCO_USERS_HOME, CUSTOM_MODEL_JAR_PATH, CUSTOM_MODEL_XML_PATH_IN_JAR, ALFRESCO_MODEL_FOLDER_REF, CUSTOM_MODEL_XML_PATH, CUSTOM_MODEL_XML_NAME;

}
