package it.drwolf.slot.prefs;

public enum PreferenceKey {

	ALFRESCO_LOCATION, ALFRESCO_ADMIN_USER, ALFRESCO_ADMIN_PWD, CUSTOM_MODEL_XML_PATH, CUSTOM_MODEL_XML_NAME, FORCE_GROUPS_PATH, FORCE_ADMIN, FORCE_USER_GROUP, FORCE_EMAIL_HOSTNAME, FORCE_EMAIL_FROM;

}
